import { movie } from "./types/types";
export const movies: movie[] = [
  {
    id: "asd",
    name: "Eternal Sunshine of the Spotless Mind",
    posterPhoto: "../assets/enternal-logo.jpg",
    bgPhoto: "../assets/eternal-sunshine-of-the-spotless-mind.jpg",
    length: 190,
    plot: "adasd sdfi asdi fasi dfao isdf aius dfai sud fhpi",
    releaseYear: 1999,
    genres: [
      { id: 1, name: "Drama" },
      { id: 2, name: "Romance" },
      { id: 3, name: "Sci-Fi" },
    ],
    avgRating: 8.7,
  },
  {
    id: "interstellar-2014",
    name: "Interstellar",
    posterPhoto: "../assets/interstellar-logo.jpg",
    bgPhoto: "../assets/interstellar-bg.jpg",
    length: 169,
    plot: "Explorers travel through a wormhole in space to ensure humanity’s survival.",
    releaseYear: 2014,
    genres: [
      { id: 3, name: "Sci-Fi" },
      { id: 1, name: "Drama" },
    ],
    avgRating: 8.2,
  },
  {
    id: "dark-knight-2008",
    name: "The Dark Knight",
    posterPhoto: "../assets/dark-knight-logo.jpg",
    bgPhoto: "../assets/dark-knight-bg.jpg",
    length: 152,
    plot: "Batman faces the Joker, a criminal mastermind bent on chaos in Gotham City.",
    releaseYear: 2008,
    genres: [
      { id: 5, name: "Action" },
      { id: 6, name: "Crime" },
    ],
    avgRating: 8.8,
  },
  {
    id: "parasite-2019",
    name: "Parasite",
    posterPhoto: "../assets/parasite-logo.jpg",
    bgPhoto: "../assets/parasite-bg.jpg",
    length: 132,
    plot: "A poor family schemes to infiltrate a wealthy household with unexpected consequences.",
    releaseYear: 2019,
    genres: [
      { id: 4, name: "Thriller" },
      { id: 1, name: "Drama" },
    ],
    avgRating: 9,
  },
  {
    id: "matrix-1999",
    name: "The Matrix",
    posterPhoto: "../assets/matrix-logo.jpg",
    bgPhoto: "../assets/matrix-bg.jpg",
    length: 136,
    plot: "A hacker discovers the reality he lives in is a simulated world controlled by machines.",
    releaseYear: 1999,
    genres: [
      { id: 3, name: "Sci-Fi" },
      { id: 5, name: "Action" },
    ],
    avgRating: 8.1,
  },
  {
    id: "whiplash-2014",
    name: "Whiplash",
    posterPhoto: "../assets/whiplash-logo.jpg",
    bgPhoto: "../assets/whiplash-bg.jpg",
    length: 106,
    plot: "A young drummer is pushed to his limits by an abusive but brilliant music instructor.",
    releaseYear: 2014,
    genres: [{ id: 1, name: "Drama" }],
    avgRating: 7,
  },
];
